services :
  db:
    image: docker.io/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB_NAME
  admin:
    image: docker.io/adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
